on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Build
      run: go build -v ./...

    - run: "go vet ./..."
  
    - name: Lint
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"
        install-go: false
        cache-key: ${{ matrix.go }}

    - name: Test
      run: go test -v -coverprofile=coverage.txt ./...

  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Update report card
      uses: creekorful/goreportcard-action@v1.0
