on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install dependencies
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: |
        go vet ./...
        staticcheck ./...

    - name: Test
      run: go test -v -coverprofile=coverage.txt ./...

  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Update report card
      uses: creekorful/goreportcard-action@v1.0
